import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const careersData = [
  {
    name: "Contaduría y Finanzas",
    rvoe: "RVOE/202174LCyF",
    durationMonths: 40,
    curriculum: [
      { cuatri: 1, subjects: ["FUNDAMENTOS DE CONTABILIDAD", "COMPUTACIÓN I", "MATEMÁTICAS", "FUNDAMENTOS DE ADMINISTRACIÓN", "FUNDAMENTOS DE DERECHO", "INGLÉS I", "TALLER: RESPONSABILIDAD Y ÉXITO ACADÉMICO"] },
      { cuatri: 2, subjects: ["CONTABILIDAD ADMINISTRATIVA", "COMPUTACIÓN II", "ESTADÍSTICA I", "PROCESO ADMINISTRATIVO", "DERECHO MERCANTIL", "INGLÉS II", "TALLER: FINANZAS PERSONALES"] },
      { cuatri: 3, subjects: ["CONTABILIDAD DE COSTOS I", "COMPUTACIÓN Y NEGOCIOS", "ESTADÍSTICA II", "PLANEACIÓN ESTRATÉGICA", "DERECHO FISCAL", "INGLÉS III", "TALLER: LECTURA Y REDACCIÓN"] },
      { cuatri: 4, subjects: ["CONTABILIDAD DE COSTOS II", "COMPUTACIÓN APLICADA A LA CONTADURÍA", "MERCADOTECNIA", "ORGANIZACIÓN INTELIGENTE", "DERECHO LABORAL", "INGLÉS IV", "TALLER: ORATORIA"] },
      { cuatri: 5, subjects: ["IMPUESTOS", "AUDITORÍA ADMINISTRATIVA", "FINANZAS", "DESARROLLO DE HABILIDADES DIRECTIVAS", "SEGURIDAD SOCIAL", "INGLÉS V", "TALLER: HERRAMIENTAS FINANCIERAS CON EXCEL"] },
      { cuatri: 6, subjects: ["CONTABILIDAD DE SOCIEDADES", "AUDITORÍA DE ESTADOS FINANCIEROS", "FINANZAS PÚBLICAS", "COMERCIO INTERNACIONAL", "ÉTICA", "ANÁLISIS DEL DESARROLLO NACIONAL", "TALLER: GESTIÓN DEL PATRIMONIO"] },
      { cuatri: 7, subjects: ["CONTABILIDAD DE ASOCIACIONES Y SOCIEDADES CIVILES", "AUDITORÍA GUBERNAMENTAL", "FINANZAS BURSÁTILES", "PROCEDIMIENTOS FISCALES", "METODOLOGÍA DE LA INVESTIGACIÓN", "EXPRESIÓN ORAL Y ESCRITA", "TALLER: PLANEACIÓN FINANCIERA Y PRESUPUESTOS"] },
      { cuatri: 8, subjects: ["CONTABILIDAD POR ÁREA DE RESPONSABILIDAD", "CONTRALORÍA", "FINANZAS CORPORATIVAS", "ADMINISTRACIÓN DE SUELDOS Y SALARIOS", "DISEÑO DE PROYECTOS DE INVESTIGACIÓN", "ADMINISTRACIÓN DE RECURSOS HUMANOS", "TALLER: EVALUACIÓN DE PROYECTOS DE INVERSIÓN"] },
      { cuatri: 9, subjects: ["CONTABILIDAD BANCARIA", "PORTAFOLIO DE INVERSIONES", "FINANZAS INTERNACIONALES", "PRESUPUESTOS Y CONTROL PRESUPUESTAL", "SEMINARIO DE TESIS I", "TALLER: APLICACIÓN DE LA IA EN LA CONTABILIDAD"] },
      { cuatri: 10, subjects: ["CONTABILIDAD INTERNACIONAL", "TÓPICOS Y PERSPECTIVAS DE LA CONTABILIDAD", "FORMULACIÓN Y EVALUACIÓN DE PROYECTOS", "DESARROLLO ORGANIZACIONAL", "SEMINARIO DE TESIS II", "TALLER: GESTIÓN DE RIESGOS FINANCIEROS"] },
    ]
  },
  {
    name: "Administración de Empresas",
    rvoe: "RVOE/202173LAE",
    durationMonths: 40,
    curriculum: [
      { cuatri: 1, subjects: ["FUNDAMENTOS DE ADMINISTRACIÓN", "FUNDAMENTOS DE CONTABILIDAD", "COMPUTACIÓN I", "MATEMÁTICAS", "FUNDAMENTOS DE DERECHO", "INGLÉS I", "TALLER: RESPONSABILIDAD Y ÉXITO ACADÉMICO"] },
      { cuatri: 2, subjects: ["PROCESO ADMINISTRATIVO", "CONTABILIDAD ADMINISTRATIVA", "COMPUTACIÓN II", "ESTADÍSTICA I", "DERECHO MERCANTIL", "INGLÉS II", "TALLER: FINANZAS PERSONALES"] },
      { cuatri: 3, subjects: ["PLANEACIÓN ESTRATÉGICA", "CONTABILIDAD DE COSTOS", "COMPUTACIÓN Y NEGOCIOS", "ESTADÍSTICA II", "DERECHO FISCAL", "INGLÉS III", "TALLER: LECTURA Y REDACCIÓN"] },
      { cuatri: 4, subjects: ["ORGANIZACIÓN INTELIGENTE", "ADMINISTRACIÓN FINANCIERA I", "MERCADOTECNIA I", "MÉTODOS CUANTITATIVOS EN ADMINISTRACIÓN", "DERECHO LABORAL", "INGLÉS IV", "TALLER: ORATORIA"] },
      { cuatri: 5, subjects: ["TEORÍAS ADMINISTRATIVAS CONTEMPORÁNEAS", "ADMINISTRACIÓN FINANCIERA II", "MERCADOTECNIA II", "MICROECONOMÍA", "SEGURIDAD SOCIAL", "INGLÉS V", "TALLER: LENGUA DE SEÑAS"] },
      { cuatri: 6, subjects: ["CREATIVIDAD GERENCIAL", "AUDITORÍA ADMINISTRATIVA", "INVESTIGACIÓN DE MERCADOS", "MACROECONOMÍA", "ANÁLISIS DEL DESARROLLO NACIONAL", "TALLER: DESARROLLO DE HABILIDADES GERENCIALES"] },
      { cuatri: 7, subjects: ["ADMINISTRACIÓN DE CALIDAD", "SEMINARIO DE FINANZAS", "PROMOCIÓN EN LA MERCADOTECNIA", "METODOLOGÍA DE LA INVESTIGACIÓN", "ÉTICA", "TALLER: APLICACIÓN DE LA IA EN LA ADMINISTRACIÓN"] },
      { cuatri: 8, subjects: ["ADMINISTRACIÓN DE RECURSOS HUMANOS", "FORMULACIÓN Y EVALUACIÓN DE PROYECTOS", "MERCADOTECNIA INTERNACIONAL", "DISEÑO DEL PROYECTO DE INVESTIGACIÓN", "EXPRESIÓN ORAL Y ESCRITA", "TALLER: INNOVACIÓN Y EMPRENDIMIENTO EMPRESARIAL"] },
      { cuatri: 9, subjects: ["ADMINISTRACIÓN DE SUELDOS Y SALARIOS", "FORMACIÓN DE EMPRENDEDORES", "COMERCIO INTERNACIONAL", "SEMINARIO DE TESIS I", "COMUNICACIÓN ADMINISTRATIVA", "TALLER: NEGOCIACIÓN Y RESOLUCIÓN DE CONFLICTOS"] },
      { cuatri: 10, subjects: ["ADMINISTRACIÓN PÚBLICA", "DESARROLLO ORGANIZACIONAL", "RELACIONES PÚBLICAS", "SEMINARIO DE TESIS II", "TALLER: MARKETING DIGITAL Y ESTRATEGIAS COMERCIALES"] },
    ]
  },
  {
    name: "Ingeniería en Sistemas Computacionales",
    rvoe: "RVOE/202177LISC",
    durationMonths: 40,
    curriculum: [
      { cuatri: 1, subjects: ["CÁLCULO DIFERENCIAL", "FUNDAMENTOS DE PROGRAMACIÓN", "MATEMÁTICAS DISCRETAS", "INTRODUCCIÓN A LA INGENIERÍA EN SISTEMAS COMPUTACIONALES", "FUNDAMENTOS DE INVESTIGACIÓN", "INGLÉS I", "TALLER: COMPUTACIÓN"] },
      { cuatri: 2, subjects: ["CÁLCULO INTEGRAL", "PROGRAMACIÓN ORIENTADA A OBJETOS", "CONTABILIDAD FINANCIERA", "ÁLGEBRA LINEAL", "CULTURA EMPRESARIAL", "INGLÉS II", "TALLER: RESPONSABILIDAD Y ÉXITO ACADÉMICO"] },
      { cuatri: 3, subjects: ["CÁLCULO VECTORIAL", "PROBABILIDAD Y ESTADÍSTICA", "QUÍMICA", "INVESTIGACIÓN DE OPERACIONES", "ESTRUCTURA DE DATOS", "INGLÉS III", "TALLER: LECTURA Y REDACCIÓN"] },
      { cuatri: 4, subjects: ["ECUACIONES DIFERENCIALES", "TÓPICOS AVANZADOS DE PROGRAMACIÓN", "FÍSICA GENERAL", "SISTEMAS OPERATIVOS", "FUNDAMENTOS DE BASES DE DATOS", "INGLÉS IV", "TALLER: FINANZAS PERSONALES"] },
      { cuatri: 5, subjects: ["MÉTODOS NUMÉRICOS", "SIMULACIÓN", "FUNDAMENTOS DE INGENIERÍA DEL SOFTWARE", "TALLER DE SISTEMAS OPERATIVOS", "TALLER DE BASE DE DATOS", "PRINCIPIOS ELÉCTRICOS Y APLICACIONES DIGITALES", "TALLER: PROGRAMACIÓN ORIENTADA A OBJETOS"] },
      { cuatri: 6, subjects: ["FUNDAMENTOS DE TELECOMUNICACIONES", "LENGUAJES Y AUTÓMATAS I", "INGENIERÍA DEL SOFTWARE", "REDES DE COMPUTADORAS", "ADMINISTRACIÓN DE BASE DE DATOS", "ARQUITECTURA DE COMPUTADORAS", "TALLER: DESARROLLO DE SOFTWARE SEGURO"] },
      { cuatri: 7, subjects: ["LENGUAJE DE INTERFAZ", "LENGUAJES Y AUTÓMATAS II", "GESTIÓN DE PROYECTOS DE SOFTWARE", "CONMUTACIÓN Y ENRUTAMIENTO DE REDES DE DATOS", "SISTEMAS PROGRAMABLES", "GRAFICACIÓN", "TALLER: DESARROLLO DE APPS"] },
      { cuatri: 8, subjects: ["PROGRAMACIÓN Y LÓGICA FUNCIONAL", "PROGRAMACIÓN WEB", "ADMINISTRACIÓN DE REDES", "PATRONES DE ANÁLISIS Y DISEÑO", "DESARROLLO SUSTENTABLE", "ENTORNO DE DESARROLLO DE SOFTWARE", "TALLER: SENSORES Y ACTUADORES"] },
      { cuatri: 9, subjects: ["INTELIGENCIA ARTIFICIAL", "REINGENIERÍA DEL SOFTWARE", "DESARROLLO DE SOFTWARE ÁGIL", "SISTEMAS DISTRIBUIDOS", "AUDITORÍA DE SISTEMAS INFORMÁTICOS", "SEMINARIO DE TESIS I", "TALLER: RESPUESTA ANTE INCIDENTES DE SEGURIDAD"] },
      { cuatri: 10, subjects: ["PROGRAMACIÓN AVANZADA", "PRUEBAS Y MANTENIMIENTO DE SOFTWARE", "SEMINARIO DE TESIS II", "SEGURIDAD EN DESARROLLO DE SOFTWARE", "PRODUCCIÓN MULTIMEDIA DIGITAL", "MÉTRICAS Y ESTIMACIÓN DE SOFTWARE", "TALLER: INNOVACIÓN Y EMPRENDIMIENTO"] },
    ]
  },
  {
    name: "Ingeniería Industrial",
    rvoe: "RVOE/202176LII",
    durationMonths: 40,
    curriculum: [
      { cuatri: 1, subjects: ["INTRODUCCIÓN A LA INGENIERÍA INDUSTRIAL", "ÁLGEBRA", "COMPUTACIÓN BÁSICA", "FUNDAMENTOS DE ADMINISTRACIÓN", "FUNDAMENTOS DE CONTABILIDAD", "INGLÉS I", "TALLER: RESPONSABILIDAD Y ÉXITO ACADÉMICO"] },
      { cuatri: 2, subjects: ["QUÍMICA BÁSICA", "CÁLCULO DIFERENCIAL", "DISEÑO ASISTIDO POR COMPUTADORA", "ORGANIZACIÓN INTELIGENTE", "CONTABILIDAD DE COSTOS", "INGLÉS II", "TALLER: FINANZAS PERSONALES"] },
      { cuatri: 3, subjects: ["TERMODINÁMICA GENERAL", "CÁLCULO INTEGRAL", "FÍSICA GENERAL", "GEOMETRÍA ANALÍTICA", "ADMINISTRACIÓN DE RECURSOS HUMANOS", "INGLÉS III", "TALLER: LECTURA Y REDACCIÓN"] },
      { cuatri: 4, subjects: ["ESTRUCTURA Y PROPIEDADES DE LOS MATERIALES", "ECUACIONES DIFERENCIALES", "INVESTIGACIÓN DE OPERACIONES I", "PROBABILIDAD Y ESTADÍSTICA", "MERCADOTECNIA", "DERECHO LABORAL", "TALLER: ORATORIA"] },
      { cuatri: 5, subjects: ["MECÁNICA", "MÉTODOS NUMÉRICOS", "INVESTIGACIÓN DE OPERACIONES II", "ESTADÍSTICA APLICADA", "ECONOMÍA", "SEMINARIO DE ÉTICA", "TALLER: LENGUA DE SEÑAS"] },
      { cuatri: 6, subjects: ["MEDICIÓN EN INGENIERÍA", "INGENIERÍA ELÉCTRICA", "ANÁLISIS DE DECISIONES", "DISEÑO Y DESARROLLO DE SISTEMAS", "PLANEACIÓN ESTRATÉGICA", "EXPRESIÓN ORAL Y ESCRITA", "TALLER: DISEÑO DE LAYOUTS INDUSTRIALES"] },
      { cuatri: 7, subjects: ["HIGIENE Y SEGURIDAD INDUSTRIAL", "INTRODUCCIÓN A LOS SISTEMAS ELECTROMECÁNICOS", "INGENIERÍA DE MÉTODOS Y TIEMPO", "SISTEMAS DE PRODUCCIÓN", "INSTALACIONES INDUSTRIALES", "METODOLOGÍA DE LA INVESTIGACIÓN", "TALLER: SIMULACIÓN DE PROCESOS INDUSTRIALES"] },
      { cuatri: 8, subjects: ["PROCESOS DE MANUFACTURA", "GESTIÓN DE MTTO. DE EQUIPOS E INSTALACIONES", "LOGÍSTICA INDUSTRIAL Y COMERCIAL", "ORGANIZACIÓN INDUSTRIAL", "PLANEACIÓN Y CONTROL DE LA PRODUCCIÓN", "DISEÑO DEL PROYECTO DE INVESTIGACIÓN", "TALLER: INGENIERÍA DE MÉTODOS Y ESTUDIO DE TIEMPOS"] },
      { cuatri: 9, subjects: ["CONTROL DE CALIDAD", "ERGONOMÍA", "COMERCIALIZACIÓN", "GERENCIA DE CADENA DE SUMINISTROS", "PSICOLOGÍA ORGANIZACIONAL", "SEMINARIO DE TESIS I", "TALLER: GESTIÓN DE PROYECTOS CON METODOLOGÍA ÁGIL"] },
      { cuatri: 10, subjects: ["GESTIÓN DE CALIDAD", "SISTEMAS INTEGRADOS DE MANUFACTURA", "DISEÑO DE PLANTAS", "COMERCIO INTERNACIONAL", "FORMACIÓN EMPRESARIAL", "SEMINARIO DE TESIS II", "TALLER: USO DE LA IA EN LA INGENIERÍA INDUSTRIAL"] },
    ]
  },
  {
    name: "Derecho",
    rvoe: "RVOE/202175LD",
    durationMonths: 40,
    curriculum: [
      { cuatri: 1, subjects: ["HISTORIA UNIVERSAL DEL DERECHO", "EXPRESIÓN ORAL Y ESCRITA", "SOCIOLOGÍA JURÍDICA", "COMPUTACIÓN I", "INGLÉS I", "TALLER: RESPONSABILIDAD Y ÉXITO ACADÉMICO"] },
      { cuatri: 2, subjects: ["DERECHO ROMANO", "ECONOMÍA POLÍTICA", "COMPUTACIÓN II", "INGLÉS II", "INTRODUCCIÓN AL ESTUDIO DEL DERECHO", "DERECHO DE LA SEGURIDAD SOCIAL", "TALLER: FINANZAS PERSONALES"] },
      { cuatri: 3, subjects: ["DEONTOLOGÍA JURÍDICA", "DERECHO ECONÓMICO", "DERECHO PENAL I", "DERECHO MERCANTIL I", "DERECHO CIVIL I", "DERECHO INDIVIDUAL DEL TRABAJO", "TALLER: LECTURA Y REDACCIÓN"] },
      { cuatri: 4, subjects: ["FILOSOFÍA DEL DERECHO", "POLÍTICA Y ESTADO", "DERECHO PENAL II", "DERECHO MERCANTIL II", "DERECHO CIVIL II", "DERECHO COLECTIVO DEL TRABAJO", "TALLER: ORATORIA"] },
      { cuatri: 5, subjects: ["ÉTICA", "DERECHO CONSTITUCIONAL", "DERECHO PROCESAL PENAL I", "DERECHO BANCARIO", "DERECHO CIVIL III", "DERECHO FISCAL", "TALLER: LENGUA DE SEÑAS"] },
      { cuatri: 6, subjects: ["EPISTEMOLOGÍA", "DERECHOS HUMANOS I", "DERECHO PROCESAL PENAL II", "DERECHO NOTARIAL", "DERECHO CIVIL IV", "DERECHO PROCESAL FISCAL", "TALLER: TÉCNICAS DE LITIGACIÓN ORAL"] },
      { cuatri: 7, subjects: ["METODOLOGÍA DE LA INVESTIGACIÓN", "DERECHOS HUMANOS II", "SEMINARIO DE DERECHO PENAL", "SOCIEDAD ANÓNIMA", "DERECHO PROCESAL CIVIL I", "DERECHO ADMINISTRATIVO", "TALLER: ARGUMENTACIÓN JURÍDICA Y REDACCIÓN DE DOCUMENTOS LEGALES"] },
      { cuatri: 8, subjects: ["DISEÑO DEL PROYECTO DE INVESTIGACIÓN", "DERECHO DE AMPARO", "DELITOS ESPECIALES", "CONTRATOS MERCANTILES", "DERECHO PROCESAL CIVIL II", "DERECHO INTERNACIONAL PÚBLICO", "TALLER: MEDIACIÓN Y RESOLUCIÓN DE CONFLICTOS"] },
      { cuatri: 9, subjects: ["SEMINARIO DE TESIS I", "AMPARO EN MATERIA CIVIL", "CRIMINOLOGÍA", "DERECHO CORPORATIVO", "SEMINARIO DE DERECHO CIVIL", "DERECHO INTERNACIONAL PRIVADO", "AGRARISMO EN MÉXICO", "TALLER: ÉTICA PROFESIONAL Y RESPONSABILIDAD LEGAL"] },
      { cuatri: 10, subjects: ["SEMINARIO DE TESIS II", "AMPARO EN MATERIA PENAL", "MEDICINA LEGAL", "DERECHO ECOLÓGICO", "DERECHO ADUANERO", "DERECHO AGRARIO", "TALLER: DERECHO DIGITAL Y PROTECCIÓN DE DATOS"] },
    ]
  },
  {
    name: "Administración de Empresas Turísticas",
    rvoe: "RVOE/202172LAET",
    durationMonths: 40,
    curriculum: [
      { cuatri: 1, subjects: ["FUNDAMENTOS DE ADMINISTRACIÓN", "FUNDAMENTOS DE CONTABILIDAD", "COMPUTACIÓN I", "MATEMÁTICAS", "INTRODUCCIÓN AL TURISMO", "INGLÉS I", "TALLER: RESPONSABILIDAD Y ÉXITO ACADÉMICO"] },
      { cuatri: 2, subjects: ["PROCESO ADMINISTRATIVO", "CONTABILIDAD ADMINISTRATIVA", "COMPUTACIÓN II", "ESTADÍSTICA", "SERVICIO DE ALIMENTOS Y BEBIDAS", "INGLÉS II", "TALLER: FINANZAS PERSONALES"] },
      { cuatri: 3, subjects: ["PLANEACIÓN ESTRATÉGICA", "CONTABILIDAD DE COSTOS", "COMPUTACIÓN Y NEGOCIOS", "GASTRONOMÍA", "DESARROLLO ORGANIZACIONAL", "INGLÉS III", "TALLER: LECTURA Y REDACCIÓN"] },
      { cuatri: 4, subjects: ["ORGANIZACIÓN INTELIGENTE", "ADMINISTRACIÓN FINANCIERA I", "MERCADOTECNIA", "MÉTODOS CUANTITATIVOS EN ADMINISTRACIÓN", "DERECHO LABORAL", "INGLÉS IV", "TALLER: ORATORIA"] },
      { cuatri: 5, subjects: ["TEORÍAS ADMINISTRATIVAS CONTEMPORÁNEAS", "ADMINISTRACIÓN FINANCIERA II", "MERCADOTECNIA DE PRODUCTOS TURÍSTICOS", "PRODUCTOS Y SERVICIOS TURÍSTICOS", "AGENCIAS DE VIAJES", "INGLÉS V", "TALLER: LENGUA DE SEÑAS"] },
      { cuatri: 6, subjects: ["CREATIVIDAD GERENCIAL", "AUDITORÍA ADMINISTRATIVA", "INVESTIGACIÓN DE MERCADOS", "ECOTURISMO", "ÉTICA", "TALLER: DESARROLLO DE HABILIDADES GERENCIALES"] },
      { cuatri: 7, subjects: ["CALIDAD DEL SERVICIO TURÍSTICO", "SEGURIDAD E HIGIENE", "ORGANIZACIÓN Y OPERACIÓN DE EVENTOS", "ANIMACIÓN Y RECREACIÓN", "TURISMO DE REUNIONES", "TALLER: TURISMO ACCESIBLE/ESTRATEGIAS PARA LA INCLUSIÓN"] },
      { cuatri: 8, subjects: ["ADMINISTRACIÓN DE RECURSOS HUMANOS", "FORMULACIÓN Y EVALUACIÓN DE PROYECTOS", "SERVICIO DE TRANSPORTE", "PLANIFICACIÓN TURÍSTICA", "COMUNICACIÓN ADMINISTRATIVA", "TALLER: IA APLICADA A LA ADMINISTRACIÓN TURÍSTICA"] },
      { cuatri: 9, subjects: ["ADMINISTRACIÓN DE SUELDOS Y SALARIOS", "FORMACIÓN DE EMPRENDEDORES", "TURISMO SOCIAL", "DESARROLLO SUSTENTABLE DEL TURISMO", "TALLER: TURISMO SOSTENIBLE Y RESPONSABILIDAD SOCIAL"] },
      { cuatri: 10, subjects: ["SEMINARIO DE HOTELERÍA", "GEOGRAFÍA TURÍSTICA", "RELACIONES PÚBLICAS", "SEMINARIO DE TESIS", "TALLER: MARKETING DIGITAL Y ESTRATEGIAS COMERCIALES"] },
    ]
  }
];

async function main() {
  console.log("Iniciando seed del currículum (Niveles, Carreras, Materias)...");
  
  // Buscar o crear la escuela base
  let school = await prisma.school.findFirst();
  if (!school) {
    school = await prisma.school.create({
      data: {
        name: "Universidad Aztlán - Playa del Carmen",
        email: "info@universidadaztlan.edu.mx"
      }
    });
  }

  // Crear el Nivel Académico
  let academicLevel = await prisma.academicLevel.findFirst({
    where: { name: "Licenciaturas" }
  });
  if (!academicLevel) {
    academicLevel = await prisma.academicLevel.create({
      data: {
        name: "Licenciaturas",
        description: "Programas de Licenciatura en modalidades SMART y Ejecutiva",
        schoolId: school.id
      }
    });
  }

  let index = 1;

  for (const careerData of careersData) {
    // 1. Buscar o crear la carrera
    let career = await prisma.career.findFirst({
      where: { name: careerData.name, schoolId: school.id }
    });
    
    if (!career) {
      career = await prisma.career.create({
        data: {
          name: careerData.name,
          rvoe: careerData.rvoe,
          durationMonths: careerData.durationMonths,
          schoolId: school.id,
          academicLevelId: academicLevel.id
        }
      });
      console.log(`✅ Carrera creada: ${career.name}`);
    } else {
      console.log(`⚡ Carrera ya existe: ${career.name}`);
    }

    // 2. Crear las materias para cada cuatrimestre
    for (const term of careerData.curriculum) {
      let subjIndex = 1;
      for (const subjectName of term.subjects) {
        // Generar un código único simple que no tenga espacios ni caracteres raros
        const code = `SUBJ-${index}-${term.cuatri}-${subjIndex}`;

        // Upsert materia
        await prisma.subject.upsert({
          where: {
            schoolId_code: {
              schoolId: school.id,
              code: code
            }
          },
          update: {
            name: subjectName,
            careerId: career.id,
            cuatrimestre: term.cuatri,
            credits: 10
          },
          create: {
            name: subjectName,
            code: code,
            schoolId: school.id,
            careerId: career.id,
            cuatrimestre: term.cuatri,
            credits: 10
          }
        });
        subjIndex++;
      }
    }
    index++;
  }

  console.log("¡Seed de currículum completado con éxito!");
}

main()
  .catch(e => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
